name: Review

on: [pull_request]

jobs:
  build:

    runs-on: macos-13-arm64

    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.2.app'
    - name: bundle install
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle install
        bundle exec fastlane review
